### ISSUE TITLE
[BUG] "this should not appear" backstory

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#45]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
a newborn that was invited into the clan has a "thiss hould not appear" backstory. clicking it crashes the game

**Grade**: (only select one)
- important - crashes game when the history is clicked

**Reproduce**
1. exile a pregnant cat
2. invite them back when they give birth
3. check their kits' profiles

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/47aea346-9e11-4b3e-9b0f-9c58092711f0)

stderr:
root - CRITICAL - main.py / log_crash / 114 - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\main.py", line 311, in <module>
    game.all_screens[game.current_screen].handle_event(event)
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 196, in handle_event
    self.toggle_history_tab()
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 999, in toggle_history_tab
    self.update_disabled_buttons_and_text()
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 1901, in update_disabled_buttons_and_text
    self.history_text_box = UITextBoxTweaked(self.get_all_history_text(),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 1073, in get_all_history_text
    life_history = [str(self.get_backstory_text())]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 1114, in get_backstory_text
    bs_blurb = BACKSTORIES["backstories"][self.the_cat.backstory]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'outsider'
Traceback (most recent call last):
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\main.py", line 311, in <module>
    game.all_screens[game.current_screen].handle_event(event)
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 196, in handle_event
    self.toggle_history_tab()
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 999, in toggle_history_tab
    self.update_disabled_buttons_and_text()
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 1901, in update_disabled_buttons_and_text
    self.history_text_box = UITextBoxTweaked(self.get_all_history_text(),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 1073, in get_all_history_text
    life_history = [str(self.get_backstory_text())]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Leafy\Downloads\clangen-leader-den\clangen-leader-den\scripts\screens\ProfileScreen.py", line 1114, in get_backstory_text
    bs_blurb = BACKSTORIES["backstories"][self.the_cat.backstory]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'outsider'

**Comment by scribblecrumb** [comment]
Failed to replicate, either the issue was fixed when I fixed other bugs or it's unrelated to pregnant cat exile and return.  Please report again if you encounter it again!
