### ISSUE TITLE
Can't Search for Lost Apprentice that was Lost on Same Moon[BUG] 

### ISSUE THREAD

**Issue by thunderingboom** [scribblecrumb/clangen#52]
**Type**: Code

**Describe the bug**
Lost an apprentice on a patrol, tried to search for them on the same moon and the game keeps crashing when I do. I unfortunately do not have the patrol ID that led to the apprentice being lost.

**Grade**: Game-breaking 

**Reproduce**
Lose an apprentice on patrol and during the same moon, search for the apprentice via the leader's den. The game will crash.

**Patrol ID + Outcome Print (if applicable)**: Traceback (most recent call last):
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\main.py", line 307, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\screens\EventsScreen.py", line 415, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\screens\Screens.py", line 218, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\game_structure\propagating_thread.py", line 23, in join
    raise self.exc
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\game_structure\propagating_thread.py", line 16, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\screens\Screens.py", line 190, in _work_target
    raise exp
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\screens\Screens.py", line 184, in _work_target
    target(*args)
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\events.py", line 123, in one_moon
    self.handle_lead_den_event()
  File "C:\Users\x\Downloads\Gen\clangen-leader-den\clangen-leader-den\scripts\events.py", line 314, in handle_lead_den_event
    chosen_event = random.choice(events)
  File "C:\Users\x\AppData\Local\Programs\Thonny\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Commit # or Game Version Number**: 
Downloaded as of today

**Comment by thunderingboom** [comment]
This apprentice is just cursed??? I cannot search for them no matter what moon, they just crash the game.
