### ISSUE TITLE
gen_med_rescue8 results in a crash

### ISSUE THREAD

**Issue by ZrainydayXXX** [scribblecrumb/clangen#54]
**Type**: Code

**Describe the bug**
When proceeding and succeeding in gen_med_rescue8, you get a crash

**Grade**:
- Game-breaking

**Reproduce**
1. Send out a solo medicine cat
2. Get gen_med_rescue8
3. Click proceed and get the success outcome

**Patrol ID + Outcome Print (if applicable)**:
Patrol Leader: Blueleaf
Random Cat: Blueleaf
Total Number of Possible Patrols | normal: 31, romantic: 0 
starting chance: 45 | EX_updated chance: 89
Blueleaf updated chance to 89 |
PATROL ID: gen_med_rescue8 | SUCCESS: True

**Commit # or Game Version Number**: 
#f686206

**Additional context**
Crash log:

root - CRITICAL - main.py / log_crash / 114 - Uncaught exception
Traceback (most recent call last):
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\main.py", line 307, in <module>
    game.all_screens[game.current_screen].on_use()
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\PatrolScreen.py", line 963, in on_use
    self.loading_screen_on_use(self.proceed_patrol_thread, self.open_patrol_complete_screen, (350, 500))
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 212, in loading_screen_on_use
    work_thread.join()
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 23, in join
    raise self.exc
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 16, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 184, in _work_target
    raise exp
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 178, in _work_target
    target(*args)
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\PatrolScreen.py", line 604, in run_patrol_proceed
    self.display_text, self.results_text, self.outcome_art = self.patrol_obj.proceed_patrol("proceed")
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol.py", line 110, in proceed_patrol
    return self.determine_outcome(antagonize=(path == "antag"))
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol.py", line 548, in determine_outcome
    return final_event.execute_outcome(self)
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol_outcome.py", line 202, in execute_outcome
    results.append(unpack_rel_block(Cat, self.relationship_effects, patrol, stat_cat=self.stat_cat))
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\utility.py", line 1338, in unpack_rel_block
    log1 = event.text + effect
AttributeError: 'Patrol' object has no attribute 'text'
Traceback (most recent call last):
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\main.py", line 307, in <module>
    game.all_screens[game.current_screen].on_use()
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\PatrolScreen.py", line 963, in on_use
    self.loading_screen_on_use(self.proceed_patrol_thread, self.open_patrol_complete_screen, (350, 500))
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 212, in loading_screen_on_use
    work_thread.join()
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 23, in join
    raise self.exc
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 16, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 184, in _work_target
    raise exp
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 178, in _work_target
    target(*args)
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\screens\PatrolScreen.py", line 604, in run_patrol_proceed
    self.display_text, self.results_text, self.outcome_art = self.patrol_obj.proceed_patrol("proceed")
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol.py", line 110, in proceed_patrol
    return self.determine_outcome(antagonize=(path == "antag"))
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol.py", line 548, in determine_outcome
    return final_event.execute_outcome(self)
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol_outcome.py", line 202, in execute_outcome
    results.append(unpack_rel_block(Cat, self.relationship_effects, patrol, stat_cat=self.stat_cat))
  File "c:\Users\stati\Downloads\clangen-moon-events\clangen-moon-events\scripts\utility.py", line 1338, in unpack_rel_block
    log1 = event.text + effect
AttributeError: 'Patrol' object has no attribute 'text'

**Comment by scribblecrumb** [comment]
Fixed
