### ISSUE TITLE
Crash on gen_bord_welcomingbinglegift1

### ISSUE THREAD

**Issue by ZrainydayXXX** [scribblecrumb/clangen#58]
**Type**: Code

**Describe the bug**
A crash when proceeding on gen_bord_welcomingbinglegift1 and getting the success outcome

**Grade**: (only select one)
- Game-breaking

**Reproduce**
1. Send a warrior on a border patrol
2. Get gen_bord_welcomingbinglegift1
3. Proceed on the success outcome

**Patrol ID + Outcome Print (if applicable)**:

Patrol Leader: Winterflame
Random Cat: Winterflame
Total Number of Possible Patrols | normal: 19, romantic: 0 
starting chance: 40 | EX_updated chance: 66
Winterflame updated chance to 66 |
PATROL ID: gen_bord_welcomingbinglegift1 | SUCCESS: True

**Commit # or Game Version Number**: 

0.9.0 (Hardcoded. Downloaded it about half an hour ago or so)

**Additional context**
Crash log:

root - CRITICAL - main.py / log_crash / 114 - Uncaught exception
Traceback (most recent call last):
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\main.py", line 307, in <module>        
    game.all_screens[game.current_screen].on_use()
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\PatrolScreen.py", line 963, in on_use
    self.loading_screen_on_use(self.proceed_patrol_thread, self.open_patrol_complete_screen, (350, 500))
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\Screens.py", line 212, in loading_screen_on_use
    work_thread.join()
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 23, in join
    raise self.exc
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 16, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\Screens.py", line 184, in _work_target
    raise exp
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\Screens.py", line 178, in _work_target
    target(*args)
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\PatrolScreen.py", line 604, in run_patrol_proceed
    self.display_text, self.results_text, self.outcome_art = self.patrol_obj.proceed_patrol("proceed")
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\patrol\patrol.py", line 110, in proceed_patrol
    return self.determine_outcome(antagonize=(path == "antag"))
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\patrol\patrol.py", line 548, in determine_outcome
    return final_event.execute_outcome(self)
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\patrol\patrol_outcome.py", line 187, in execute_outcome
    processed_text = event_text_adjust(Cat,
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\utility.py", line 1849, in event_text_adjust
    pronoun = choice(cat.pronouns)
AttributeError: 'list' object has no attribute 'pronouns'
Traceback (most recent call last):
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\main.py", line 307, in <module>        
    game.all_screens[game.current_screen].on_use()
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\PatrolScreen.py", line 963, in on_use
    self.loading_screen_on_use(self.proceed_patrol_thread, self.open_patrol_complete_screen, (350, 500))
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\Screens.py", line 212, in loading_screen_on_use
    work_thread.join()
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 23, in join
    raise self.exc
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 16, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\Screens.py", line 184, in _work_target
    raise exp
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\Screens.py", line 178, in _work_target
    target(*args)
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\screens\PatrolScreen.py", line 604, in run_patrol_proceed
    self.display_text, self.results_text, self.outcome_art = self.patrol_obj.proceed_patrol("proceed")
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\patrol\patrol.py", line 110, in proceed_patrol
    return self.determine_outcome(antagonize=(path == "antag"))
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\patrol\patrol.py", line 548, in determine_outcome
    return final_event.execute_outcome(self)
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\patrol\patrol_outcome.py", line 187, in execute_outcome
    processed_text = event_text_adjust(Cat,
  File "c:\Users\stati\Downloads\clangen-moon-events2\clangen-moon-events\scripts\utility.py", line 1849, in event_text_adjust
    pronoun = choice(cat.pronouns)
AttributeError: 'list' object has no attribute 'pronouns'

Note: Was doing a loner challenge

**Screenshots**

The cat who got the crash:
![image](https://github.com/scribblecrumb/clangen/assets/77426212/bf01d806-ffc0-4887-a05d-cef78dfc3538)

**Comment by scribblecrumb** [comment]
fixed
