### ISSUE TITLE
[BUG] Interacting with Cat Met in Moon Event Crashes Game

### ISSUE THREAD

**Issue by thunderingboom** [scribblecrumb/clangen#68]
**Type**: Code

**Describe the bug**:
Met an outsider in a moon event and on same moon tried to invite/hunt/drive off from Leader's Den and the game kept crashing.
Traceback (most recent call last):
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\main.py", line 307, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\EventsScreen.py", line 415, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 218, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 23, in join
    raise self.exc
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 16, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 190, in _work_target
    raise exp
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 184, in _work_target
    target(*args)
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\events.py", line 114, in one_moon
    self.handle_lead_den_event()
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\events.py", line 381, in handle_lead_den_event
    outsider_cat.thought = event_text_adjust(Cat, cat_dict["new_thought"], outsider_cat, clan=game.clan)
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\utility.py", line 1805, in event_text_adjust
    replace_dict["m_c"] = (str(main_cat.name), choice(main_cat.pronouns))
AttributeError: 'NoneType' object has no attribute 'name'

**Grade**: Game-breaking

**Reproduce**
Meet cat in moon event.
Try to interact with cat on same moon.

**Commit # or Game Version Number**: 
Downloaded today.

**Comment by scribblecrumb** [comment]
Should be fixed!
