### ISSUE TITLE
[BUG] Game Crash Patrol?

### ISSUE THREAD

**Issue by thunderingboom** [scribblecrumb/clangen#89]
**Type**: UI

**Describe the bug**
Got this on the new camp (Ruin) for this branch when clicking proceed on this patrol?

**Grade**:
Game-breaking

**Reproduce**
1. Get this patrol
2.  Proceed on this patrol for the Ruin Camp? Unsure what happened.

**Patrol ID + Outcome Print (if applicable)**:
PATROL ID: mtn_hunt_newleaf_snowstorm3 | SUCCESS: False
Traceback (most recent call last):
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\main.py", line 334, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\PatrolScreen.py", line 963, in on_use
    self.loading_screen_on_use(self.proceed_patrol_thread, self.open_patrol_complete_screen, (350, 500))
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 219, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 191, in _work_target
    raise exp
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\Screens.py", line 185, in _work_target
    target(*args)
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\screens\PatrolScreen.py", line 604, in run_patrol_proceed
    self.display_text, self.results_text, self.outcome_art = self.patrol_obj.proceed_patrol("proceed")
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol.py", line 119, in proceed_patrol
    return self.determine_outcome(antagonize=(path == "antag"))
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol.py", line 658, in determine_outcome
    return final_event.execute_outcome(self)
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol_outcome.py", line 235, in execute_outcome
    results.append(self._handle_condition_and_scars(patrol))
  File "C:\Users\x\Downloads\Gen\clangen-moon-events\clangen-moon-events\scripts\patrol\patrol_outcome.py", line 526, in _handle_condition_and_scars
    old_injuries = list(_cat.injuries.keys())
AttributeError: 'NoneType' object has no attribute 'injuries'

**Commit # or Game Version Number**: 
Downloaded today

**Comment by thunderingboom** [comment]
I have realized this is more of an issue with the new camp rather than with this branch, apologies for posting this here.
